### ISSUE TITLE
suggestion: `map` (or map_coord) as verb for coordinate_*

### ISSUE THREAD

**Issue by yeedle** [thomasp85/pipeplotter#3]
Since the role for the `coord_*` function family is to 

> adjust the mapping from coordinates to the 2d plane of the computer screen" [^1](http://docs.ggplot2.org/current/)

I suggest using `map` as the verb for setting a `ccord` 

`coord_cartesian()` -> `map(coord = cartesian)`
`coord_fixed()` -> `map(coord = fixed)`
`coord_flip()` -> `map(coord = flip)`

etc. 

the only ones that do not fit nicely are `coord_map` and `coord_quickmap`.

**Comment by thomasp85** [comment]
I have considered this (well, actually for scale but anyway)

The problem is that `map` is a pretty loaded term in programming and functional programming especially where it describes performing an operation on each element of a list (like `lapply`). Because of this I don't think it should be introduced into pipeplotter

**Comment by yeedle** [comment]
Fair enough. Can it fall under the general act of setting (you set scales and coordinates)?  e.g. `set(coord = cartesian)`
